[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-dev',
    'npm install',
    'npm run build'
]

[phases.build]
cmds = [
    'php artisan optimize',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'bash start.sh'